### ISSUE TITLE
What is city_code

### ISSUE THREAD

**Issue by parsariyahi** [Bright98/city-province-code#1]
سلام، واژه ``city_code`` داخل فایل ها نشان دهنده چه چیزیه؟

**Comment by bright98** [comment]
سلام، شرکت پست برای هر شهر و روستا کد مخصوصی رو در نظر گرفته، که براساس این کد، ارسال محموله پستی راحتتر انجام میشه
(بجای نام شهر که ممکنه خطا داشته باشه، کد ارسال میشه)
